apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: selenium-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub
        ports:
        - containerPort: 4444
        - containerPort: 4443
        - containerPort: 4442
        resources:
          requests:
            cpu: "0.3"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"


---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: selenium-grid
spec:
  selector:
    app: selenium-hub
  ports:
  - protocol: TCP
    name:  web
    port: 4444
    targetPort: 4444
  - protocol: TCP
    port: 4442
    targetPort: 4442
    name:  publishport
  - protocol: TCP
    port: 4443
    targetPort: 4443
    name:  subscribeport
  type: ClusterIP
