apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  namespace: selenium-grid
  labels:
    app: selenium-node-chrome
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5555"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      terminationGracePeriodSeconds: 30
      # Requires root User access
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
      #   fsGroup: 1000
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome
        env:
        - name: SE_EVENT_BUS_HOST
          value: selenium-hub.selenium-grid.svc.cluster.local
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        - name: SE_NODE_MAX_SESSIONS
          value: "2"
        ports:
        - containerPort: 5555
        livenessProbe:
          httpGet:
            path: /status
            port: 5555
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 5555
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "1"
            memory: "1"
          limits:
            cpu: "1.5"
            memory: "2Gi"
